config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: :show
  root to: "items#index"

  resources :items do
    resources :orders, only: [:index, :create]
    resources :comments, only: :create
    collection do
          get 'search'
    end
  end
  end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :items
  has_many :orders
  has_many :comments
  
  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze
  validates :password, format: { with: PASSWORD_REGEX }

  validates :nickname, presence: true
  validates :birthday, presence: true
  validates :first_name, presence: true, format: { with: /\A[ぁ-んァ-ヶ一-龥々ー]+\z/ }
  validates :last_name, presence: true, format: { with: /\A[ぁ-んァ-ヶ一-龥々ー]+\z/ }
  validates :kana_first_name, presence: true, format: { with: /\A[ァ-ヶー－]+\z/ }
  validates :kana_last_name, presence: true, format: { with: /\A[ァ-ヶー－]+\z/ }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    user = User.find(params[:id])
    @nickname = user.nickname
    @items = user.items
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<%= render "shared/header" %>

  <div class='item-contents'>
    <div class="subtitle" >
     <%= @nickname %>さんの商品一覧
    </div>
    
    <ul class='item-lists'>
      <% @items.each do |item| %>
      <li class='list'>
        <%= link_to item_path(item.id) do %>
        <div class='item-img-content'>
          <%= image_tag item.image, class: "item-img" if item.image.attached?%>

          <% if item.order != nil %>
          <div class='sold-out'>
            <span>Sold Out!!</span>
          </div>
          <% end %> 

        </div>
        <div class='item-info'>
          <h3 class='item-name'>
            <%= item.title %>
          </h3>
          <div class='item-price'>
            <span><%= item.price %>円<br><%= item.post_price.name %></span>
            <div class='star-btn'>
              <%= image_tag "star.png", class:"star-icon" %>
              <span class='star-count'>0</span>
            </div>
          </div>
        </div>
        <% end %>
      </li>
      <% end %>
<% if @items.blank? then %>
      <li class='list'>
        <%= link_to '#' do %>
          <%= image_tag "https://tech-master.s3.amazonaws.com/uploads/curriculums/images/Rails1-4/sample.jpg", class: "item-img" %>
        <div class='item-info'>
          <h3 class='item-name'>
            商品を出品してね！
          </h3>
          <div class='item-price'>
            <span>99999999円<br>(税込み)</span>
            <div class='star-btn'>
              <%= image_tag "star.png", class:"star-icon" %>
              <span class='star-count'>0</span>
            </div>
          </div>
        </div>
        <% end %>
      </li>
    <% end %>
    </ul>
    </div>

<%= render "shared/footer" %>